import { z } from 'zod';
import {
  ACCOUNT_STATUSES,
  ATTENDANCE_STATUSES,
  AUDIO_TRIGGERS,
  BALL_TYPES,
  BATTING_STYLES,
  BOOKING_STATUSES,
  DELIVERY_CHANNELS,
  DELIVERY_STATUSES,
  DUE_STATUSES,
  EXPERIENCE_LEVELS,
  EXTRA_TYPES,
  INNINGS_STATUSES,
  INVITATION_STATUSES,
  MATCH_STATUSES,
  MATCH_TYPES,
  MATCH_VISIBILITIES,
  MEMBERSHIP_STATUSES,
  PARTICIPANT_ROLES,
  PAYMENT_METHODS,
  PAYMENT_MODES,
  PAYMENT_STATUSES,
  PLAYING_ROLES,
  RATING_DIMENSIONS,
  RATING_EVENT_TYPES,
  REFUND_STATUSES,
  REPLACEMENT_STATUSES,
  RESULT_TYPES,
  SCORING_MODES,
  SIDE_LABELS,
  SUPPORT_CATEGORIES,
  SUPPORT_STATUSES,
  TEAM_MEMBER_ROLES,
  TEAM_SKILL_LEVELS,
  TEAM_STATUSES,
  TURF_STATUSES,
  USER_ROLES,
  WICKET_TYPES,
  NOTIFICATION_TYPES,
} from '../domain/constants';

const uuid = z.string().uuid();
const timestamp = z.coerce.date();
const dateOnly = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const timeOnly = z.string().regex(/^\d{2}:\d{2}(:\d{2})?$/);
const decimalString = z.union([z.string(), z.number()]).transform(String);

export const userSchema = z.object({
  user_id: uuid,
  phone_number: z.string().max(15),
  email: z.string().email().max(255).nullable().optional(),
  password_hash: z.string().max(255),
  role: z.enum(USER_ROLES),
  account_status: z.enum(ACCOUNT_STATUSES),
  phone_verified_at: timestamp.nullable().optional(),
  profile_photo_url: z.string().url().max(500).nullable().optional(),
  city: z.string().max(100).nullable().optional(),
  preferred_language: z.string().max(10).nullable().optional(),
  bfam_id: z
    .string()
    .regex(/^BF\d+$/)
    .max(15),
  google_id: z.string().max(255).nullable().optional(),
  apple_id: z.string().max(255).nullable().optional(),
  is_minor: z.boolean(),
  last_login_at: timestamp.nullable().optional(),
});

export const playerSchema = z.object({
  player_id: uuid,
  user_id: uuid,
  bfam_id: z.string().max(15),
  playing_role: z.enum(PLAYING_ROLES).nullable().optional(),
  batting_style: z.enum(BATTING_STYLES).nullable().optional(),
  bowling_style: z.string().max(30).nullable().optional(),
  experience_level: z.enum(EXPERIENCE_LEVELS),
  skill_rating: z.number().int(),
  reliability_score: decimalString,
  bio: z.string().nullable().optional(),
  date_of_birth: dateOnly.nullable().optional(),
  favorite_cricketer_name: z.string().max(100).nullable().optional(),
  favorite_cricketer_external_id: z.string().max(50).nullable().optional(),
});

export const tableSchemas = {
  users: userSchema,
  players: playerSchema,
  teams: z.object({
    team_id: uuid,
    team_name: z.string().max(100),
    team_logo_url: z.string().url().max(500).nullable().optional(),
    description: z.string().nullable().optional(),
    skill_level: z.enum(TEAM_SKILL_LEVELS).nullable().optional(),
    home_city: z.string().max(100).nullable().optional(),
    is_open_for_players: z.boolean(),
    team_status: z.enum(TEAM_STATUSES),
    created_by: uuid,
  }),
  team_members: z.object({
    team_member_id: uuid,
    team_id: uuid,
    player_id: uuid,
    role_in_team: z.enum(TEAM_MEMBER_ROLES),
    membership_status: z.enum(MEMBERSHIP_STATUSES),
    joined_at: timestamp,
    left_at: timestamp.nullable().optional(),
  }),
  team_invitations: z.object({
    invitation_id: uuid,
    team_id: uuid,
    invited_player_id: uuid,
    invited_by: uuid,
    status: z.enum(INVITATION_STATUSES),
    created_at: timestamp,
    responded_at: timestamp.nullable().optional(),
    expires_at: timestamp.nullable().optional(),
  }),
  team_join_requests: z.object({
    request_id: uuid,
    team_id: uuid,
    player_id: uuid,
    status: z.enum(INVITATION_STATUSES),
    requested_at: timestamp,
    responded_by: uuid.nullable().optional(),
  }),
  turfs: z.object({
    turf_id: uuid,
    owner_id: uuid,
    turf_name: z.string().max(150),
    description: z.string().nullable().optional(),
    address_line: z.string().max(255),
    city: z.string().max(100),
    latitude: decimalString,
    longitude: decimalString,
    ball_types_supported: z.array(z.enum(BALL_TYPES)).nullable().optional(),
    stadium_sound_enabled: z.boolean(),
    turf_status: z.enum(TURF_STATUSES),
    average_rating: decimalString.nullable().optional(),
  }),
  bookings: z.object({
    booking_id: uuid,
    turf_id: uuid,
    booked_by: uuid,
    booking_date: dateOnly,
    start_time: timeOnly,
    end_time: timeOnly,
    duration_minutes: z.number().int(),
    booking_amount: decimalString,
    booking_status: z.enum(BOOKING_STATUSES),
    payment_mode: z.enum(PAYMENT_MODES),
  }),
  matches: z.object({
    match_id: uuid,
    booking_id: uuid,
    match_name: z.string().max(150).nullable().optional(),
    organizer_id: uuid,
    match_type: z.enum(MATCH_TYPES),
    ball_type: z.enum(BALL_TYPES),
    overs_per_innings: z.number().int(),
    scoring_mode: z.enum(SCORING_MODES),
    match_status: z.enum(MATCH_STATUSES),
    visibility: z.enum(MATCH_VISIBILITIES),
    scheduled_start_time: timestamp,
  }),
  score_events: z.object({
    score_event_id: uuid,
    innings_id: uuid,
    over_number: z.number().int(),
    ball_number_in_over: z.number().int(),
    sequence_number: z.number().int(),
    runs_scored: z.number().int(),
    extra_type: z.enum(EXTRA_TYPES),
    extra_runs: z.number().int(),
    is_wicket: z.boolean(),
    wicket_type: z.enum(WICKET_TYPES).nullable().optional(),
    audio_trigger: z.enum(AUDIO_TRIGGERS),
    recorded_by: uuid,
  }),
  innings: z.object({
    innings_id: uuid,
    match_id: uuid,
    innings_number: z.number().int(),
    innings_status: z.enum(INNINGS_STATUSES),
  }),
  match_results: z.object({
    result_id: uuid,
    match_id: uuid,
    result_type: z.enum(RESULT_TYPES),
    finalized_by: uuid,
  }),
  player_rating_events: z.object({
    rating_event_id: uuid,
    player_id: uuid,
    event_type: z.enum(RATING_EVENT_TYPES),
    rating_dimension: z.enum(RATING_DIMENSIONS),
    rating_delta: decimalString,
  }),
  payments: z.object({
    payment_id: uuid,
    payer_id: uuid,
    payment_method: z.enum(PAYMENT_METHODS),
    payment_status: z.enum(PAYMENT_STATUSES),
  }),
  payment_obligations: z.object({
    obligation_id: uuid,
    booking_id: uuid,
    amount_due: decimalString,
    due_status: z.enum(DUE_STATUSES),
  }),
  refunds: z.object({ refund_id: uuid, payment_id: uuid, refund_status: z.enum(REFUND_STATUSES) }),
  match_teams: z.object({ match_team_id: uuid, match_id: uuid, side_label: z.enum(SIDE_LABELS) }),
  match_players: z.object({
    match_player_id: uuid,
    match_id: uuid,
    player_id: uuid,
    participant_role: z.enum(PARTICIPANT_ROLES),
    attendance_status: z.enum(ATTENDANCE_STATUSES),
  }),
  player_replacements: z.object({
    replacement_id: uuid,
    match_id: uuid,
    vacating_player_id: uuid,
    initiated_by: uuid,
    status: z.enum(REPLACEMENT_STATUSES),
  }),
  notifications: z.object({
    notification_id: uuid,
    user_id: uuid,
    notification_type: z.enum(NOTIFICATION_TYPES),
    delivery_channel: z.enum(DELIVERY_CHANNELS),
    delivery_status: z.enum(DELIVERY_STATUSES),
  }),
  support_tickets: z.object({
    ticket_id: uuid,
    raised_by: uuid,
    category: z.enum(SUPPORT_CATEGORIES),
    description: z.string(),
    status: z.enum(SUPPORT_STATUSES),
  }),
};
