import { DataTypes, ModelAttributes, Sequelize } from 'sequelize';
import {
  ACCOUNT_STATUSES,
  ASSIGNMENT_STATUSES,
  ATTENDANCE_STATUSES,
  AUDIO_TRIGGERS,
  BALL_TYPES,
  BATTING_STYLES,
  BLOCK_REASONS,
  BOOKING_STATUSES,
  DAY_TYPES,
  DELIVERY_CHANNELS,
  DELIVERY_STATUSES,
  DUE_STATUSES,
  EXPERIENCE_LEVELS,
  EXTRA_TYPES,
  INNINGS_STATUSES,
  INVITATION_STATUSES,
  MATCH_STATUSES,
  MATCH_TYPES,
  MATCH_VISIBILITIES,
  MEMBERSHIP_STATUSES,
  PARTICIPANT_ROLES,
  PAYMENT_METHODS,
  PAYMENT_MODES,
  PAYMENT_STATUSES,
  PLAYING_ROLES,
  RATING_DIMENSIONS,
  RATING_EVENT_TYPES,
  REFUND_STATUSES,
  REPLACEMENT_STATUSES,
  RESULT_TYPES,
  SCORING_MODES,
  SIDE_LABELS,
  SUPPORT_CATEGORIES,
  SUPPORT_STATUSES,
  TEAM_MEMBER_ROLES,
  TEAM_SKILL_LEVELS,
  TEAM_STATUSES,
  TURF_STATUSES,
  USER_ROLES,
  WICKET_TYPES,
  NOTIFICATION_TYPES,
} from '../domain/constants';

type TableModelDefinition = {
  tableName: string;
  primaryKey: string;
  attributes: ModelAttributes;
};

// ---- column helpers (mirror the style/shape used by the phase1 migration) ----
const id = (primaryKey = false, allowNull = false) => ({
  type: DataTypes.UUID,
  primaryKey,
  allowNull: primaryKey ? false : allowNull,
  ...(primaryKey ? { defaultValue: DataTypes.UUIDV4 } : {}),
});
const str = (length: number, allowNull = false) => ({ type: DataTypes.STRING(length), allowNull });
const text = (allowNull = false) => ({ type: DataTypes.TEXT, allowNull });
const dec = (precision: number, scale: number, allowNull = false, defaultValue?: number) => ({
  type: DataTypes.DECIMAL(precision, scale),
  allowNull,
  ...(defaultValue === undefined ? {} : { defaultValue }),
});
const date = (allowNull = false) => ({ type: DataTypes.DATE, allowNull });
const dateOnly = (allowNull = false) => ({ type: DataTypes.DATEONLY, allowNull });
const time = (allowNull = false) => ({ type: DataTypes.TIME, allowNull });
const smallint = (allowNull = false, defaultValue?: number) => ({
  type: DataTypes.SMALLINT,
  allowNull,
  ...(defaultValue === undefined ? {} : { defaultValue }),
});
const int = (allowNull = false, defaultValue?: number) => ({
  type: DataTypes.INTEGER,
  allowNull,
  ...(defaultValue === undefined ? {} : { defaultValue }),
});
const bool = (allowNull = false, defaultValue?: boolean) => ({
  type: DataTypes.BOOLEAN,
  allowNull,
  ...(defaultValue === undefined ? {} : { defaultValue }),
});
const json = (allowNull = false) => ({ type: DataTypes.JSON, allowNull });
const enumCol = (values: readonly string[], allowNull = false, defaultValue?: string) => ({
  type: DataTypes.ENUM(...values),
  allowNull,
  ...(defaultValue ? { defaultValue } : {}),
});
const char = (length: number, allowNull = false, defaultValue?: string) => ({
  type: DataTypes.CHAR(length),
  allowNull,
  ...(defaultValue ? { defaultValue } : {}),
});

export const tableModelDefinitions: TableModelDefinition[] = [
  {
    tableName: 'users',
    primaryKey: 'user_id',
    attributes: {
      user_id: id(true),
      phone_number: str(15),
      email: str(255, true),
      password_hash: str(255),
      role: enumCol(USER_ROLES),
      account_status: enumCol(ACCOUNT_STATUSES, false, 'ACTIVE'),
      phone_verified_at: date(true),
      profile_photo_url: str(500, true),
      city: str(100, true),
      preferred_language: str(10, true),
      bfam_id: str(15),
      google_id: str(255, true),
      apple_id: str(255, true),
      is_minor: bool(false, false),
      last_login_at: date(true),
      created_at: date(),
      updated_at: date(),
      deleted_at: date(true),
    },
  },
  {
    tableName: 'players',
    primaryKey: 'player_id',
    attributes: {
      player_id: id(true),
      user_id: id(),
      bfam_id: str(15),
      playing_role: enumCol(PLAYING_ROLES, true),
      batting_style: enumCol(BATTING_STYLES, true),
      bowling_style: str(30, true),
      experience_level: enumCol(EXPERIENCE_LEVELS, false, 'BEGINNER'),
      skill_rating: int(false, 500),
      reliability_score: dec(5, 2, false, 100),
      bio: text(true),
      date_of_birth: dateOnly(true),
      favorite_cricketer_name: str(100, true),
      favorite_cricketer_external_id: str(50, true),
      created_at: date(),
      updated_at: date(),
      deleted_at: date(true),
    },
  },
  {
    tableName: 'teams',
    primaryKey: 'team_id',
    attributes: {
      team_id: id(true),
      team_name: str(100),
      team_logo_url: str(500, true),
      description: text(true),
      skill_level: enumCol(TEAM_SKILL_LEVELS, true),
      home_city: str(100, true),
      is_open_for_players: bool(false, false),
      team_status: enumCol(TEAM_STATUSES, false, 'ACTIVE'),
      created_by: id(),
      created_at: date(),
      updated_at: date(),
      deleted_at: date(true),
    },
  },
  {
    tableName: 'team_members',
    primaryKey: 'team_member_id',
    attributes: {
      team_member_id: id(true),
      team_id: id(),
      player_id: id(),
      role_in_team: enumCol(TEAM_MEMBER_ROLES),
      membership_status: enumCol(MEMBERSHIP_STATUSES, false, 'ACTIVE'),
      joined_at: date(),
      left_at: date(true),
      // Generated (STORED) column added in the migration: NULL unless this
      // row is the team's active captain. Read-only — never write to it.
      active_captain_team_id: id(false, true),
    },
  },
  {
    tableName: 'team_invitations',
    primaryKey: 'invitation_id',
    attributes: {
      invitation_id: id(true),
      team_id: id(),
      invited_player_id: id(),
      invited_by: id(),
      status: enumCol(INVITATION_STATUSES, false, 'PENDING'),
      created_at: date(),
      responded_at: date(true),
      expires_at: date(true),
    },
  },
  {
    tableName: 'team_join_requests',
    primaryKey: 'request_id',
    attributes: {
      request_id: id(true),
      team_id: id(),
      player_id: id(),
      status: enumCol(INVITATION_STATUSES, false, 'PENDING'),
      requested_at: date(),
      responded_by: id(false, true),
    },
  },
  {
    tableName: 'turfs',
    primaryKey: 'turf_id',
    attributes: {
      turf_id: id(true),
      owner_id: id(),
      turf_name: str(150),
      description: text(true),
      address_line: str(255),
      city: str(100),
      latitude: dec(9, 6),
      longitude: dec(9, 6),
      ball_types_supported: json(true),
      stadium_sound_enabled: bool(false, true),
      turf_status: enumCol(TURF_STATUSES, false, 'ACTIVE'),
      average_rating: dec(3, 2, true),
      created_at: date(),
      updated_at: date(),
      deleted_at: date(true),
    },
  },
  {
    tableName: 'turf_pricing',
    primaryKey: 'pricing_id',
    attributes: {
      pricing_id: id(true),
      turf_id: id(),
      day_type: enumCol(DAY_TYPES),
      start_time: time(),
      end_time: time(),
      price_per_hour: dec(10, 2),
      currency: char(3, false, 'INR'),
      effective_from: dateOnly(),
      effective_to: dateOnly(true),
    },
  },
  {
    tableName: 'turf_staff_assignments',
    primaryKey: 'assignment_id',
    attributes: {
      assignment_id: id(true),
      turf_id: id(),
      staff_user_id: id(),
      permissions: json(),
      assigned_by: id(),
      status: enumCol(ASSIGNMENT_STATUSES, false, 'ACTIVE'),
      created_at: date(),
    },
  },
  {
    tableName: 'turf_availability_blocks',
    primaryKey: 'block_id',
    attributes: {
      block_id: id(true),
      turf_id: id(),
      start_datetime: date(),
      end_datetime: date(),
      reason: enumCol(BLOCK_REASONS),
      created_by: id(),
      created_at: date(),
    },
  },
  {
    tableName: 'turf_images',
    primaryKey: 'image_id',
    attributes: {
      image_id: id(true),
      turf_id: id(),
      image_url: str(500),
      display_order: smallint(false, 1),
    },
  },
  {
    tableName: 'turf_facilities',
    primaryKey: 'facility_id',
    attributes: {
      facility_id: id(true),
      turf_id: id(),
      facility_name: str(50),
    },
  },
  {
    tableName: 'turf_operating_hours',
    primaryKey: 'hours_id',
    attributes: {
      hours_id: id(true),
      turf_id: id(),
      day_of_week: smallint(),
      open_time: time(),
      close_time: time(),
    },
  },
  {
    tableName: 'bookings',
    primaryKey: 'booking_id',
    attributes: {
      booking_id: id(true),
      turf_id: id(),
      booked_by: id(),
      booking_date: dateOnly(),
      start_time: time(),
      end_time: time(),
      duration_minutes: smallint(),
      booking_amount: dec(10, 2),
      booking_status: enumCol(BOOKING_STATUSES, false, 'PENDING'),
      payment_mode: enumCol(PAYMENT_MODES),
      cancellation_reason: str(255, true),
      cancelled_at: date(true),
      cancelled_by: id(false, true),
      created_at: date(),
      updated_at: date(),
      // Generated (STORED) column added in the migration: NULL unless
      // booking_status IN ('PENDING','CONFIRMED'); backs the no-double-
      // booking unique index. Read-only — never write to it.
      active_booking_slot_key: str(191, true),
    },
  },
  {
    tableName: 'matches',
    primaryKey: 'match_id',
    attributes: {
      match_id: id(true),
      booking_id: id(),
      match_name: str(150, true),
      organizer_id: id(),
      match_type: enumCol(MATCH_TYPES),
      ball_type: enumCol(BALL_TYPES),
      overs_per_innings: smallint(),
      scoring_mode: enumCol(SCORING_MODES),
      assigned_scorer_id: id(false, true),
      match_status: enumCol(MATCH_STATUSES, false, 'OPEN'),
      visibility: enumCol(MATCH_VISIBILITIES, false, 'PRIVATE'),
      scheduled_start_time: date(),
      actual_start_time: date(true),
      actual_end_time: date(true),
      created_at: date(),
      updated_at: date(),
    },
  },
  {
    tableName: 'match_teams',
    primaryKey: 'match_team_id',
    attributes: {
      match_team_id: id(true),
      match_id: id(),
      team_id: id(false, true),
      side_label: enumCol(SIDE_LABELS),
      created_at: date(),
    },
  },
  {
    tableName: 'match_players',
    primaryKey: 'match_player_id',
    attributes: {
      match_player_id: id(true),
      match_id: id(),
      player_id: id(),
      match_team_id: id(false, true),
      participant_role: enumCol(PARTICIPANT_ROLES, false, 'PLAYER'),
      invitation_status: enumCol(INVITATION_STATUSES, false, 'PENDING'),
      attendance_status: enumCol(ATTENDANCE_STATUSES, false, 'PENDING'),
      checked_in_at: date(true),
      added_at: date(),
    },
  },
  {
    tableName: 'match_invitations',
    primaryKey: 'invitation_id',
    attributes: {
      invitation_id: id(true),
      match_id: id(),
      invited_player_id: id(),
      invited_by: id(),
      status: enumCol(INVITATION_STATUSES, false, 'PENDING'),
      sent_at: date(),
      responded_at: date(true),
      expires_at: date(true),
    },
  },
  {
    tableName: 'player_replacements',
    primaryKey: 'replacement_id',
    attributes: {
      replacement_id: id(true),
      match_id: id(),
      vacating_player_id: id(),
      replacement_player_id: id(false, true),
      initiated_by: id(),
      status: enumCol(REPLACEMENT_STATUSES, false, 'OPEN'),
      created_at: date(),
      resolved_at: date(true),
    },
  },
  {
    tableName: 'payment_obligations',
    primaryKey: 'obligation_id',
    attributes: {
      obligation_id: id(true),
      booking_id: id(),
      player_id: id(false, true),
      amount_due: dec(10, 2),
      due_status: enumCol(DUE_STATUSES, false, 'PENDING'),
      created_at: date(),
      updated_at: date(),
    },
  },
  {
    tableName: 'payments',
    primaryKey: 'payment_id',
    attributes: {
      payment_id: id(true),
      payer_id: id(),
      amount: dec(10, 2),
      currency: char(3, false, 'INR'),
      payment_method: enumCol(PAYMENT_METHODS),
      gateway: str(30),
      gateway_order_id: str(100),
      gateway_payment_id: str(100, true),
      collected_by: id(false, true),
      cash_reference: str(100, true),
      payment_status: enumCol(PAYMENT_STATUSES, false, 'PENDING'),
      initiated_at: date(),
      completed_at: date(true),
    },
  },
  {
    tableName: 'payment_allocations',
    primaryKey: 'allocation_id',
    attributes: {
      allocation_id: id(true),
      payment_id: id(),
      obligation_id: id(),
      allocated_amount: dec(10, 2),
      created_at: date(),
    },
  },
  {
    tableName: 'refunds',
    primaryKey: 'refund_id',
    attributes: {
      refund_id: id(true),
      payment_id: id(),
      refund_amount: dec(10, 2),
      reason: str(255),
      refund_status: enumCol(REFUND_STATUSES, false, 'PENDING'),
      gateway_refund_id: str(100, true),
      initiated_by: id(),
      created_at: date(),
      completed_at: date(true),
    },
  },
  {
    tableName: 'payment_events',
    primaryKey: 'event_id',
    attributes: {
      event_id: id(true),
      payment_id: id(),
      event_type: str(50),
      raw_payload: json(),
      received_at: date(),
    },
  },
  {
    tableName: 'innings',
    primaryKey: 'innings_id',
    attributes: {
      innings_id: id(true),
      match_id: id(),
      innings_number: smallint(),
      batting_match_team_id: id(),
      bowling_match_team_id: id(),
      total_runs: int(false, 0),
      total_wickets: smallint(false, 0),
      overs_completed: dec(4, 1, false, 0),
      innings_status: enumCol(INNINGS_STATUSES, false, 'NOT_STARTED'),
      target_runs: int(true),
      created_at: date(),
      updated_at: date(),
    },
  },
  {
    tableName: 'score_events',
    primaryKey: 'score_event_id',
    attributes: {
      score_event_id: id(true),
      innings_id: id(),
      over_number: smallint(),
      ball_number_in_over: smallint(),
      sequence_number: int(),
      striker_player_id: id(),
      non_striker_player_id: id(false, true),
      bowler_player_id: id(),
      runs_scored: smallint(false, 0),
      extra_type: enumCol(EXTRA_TYPES, false, 'NONE'),
      extra_runs: smallint(false, 0),
      is_wicket: bool(false, false),
      wicket_type: enumCol(WICKET_TYPES, true),
      dismissed_player_id: id(false, true),
      fielder_player_id: id(false, true),
      audio_trigger: enumCol(AUDIO_TRIGGERS, false, 'NONE'),
      recorded_by: id(),
      recorded_at: date(),
      is_corrected: bool(false, false),
      correction_reference_id: id(false, true),
    },
  },
  {
    tableName: 'match_results',
    primaryKey: 'result_id',
    attributes: {
      result_id: id(true),
      match_id: id(),
      winning_match_team_id: id(false, true),
      result_type: enumCol(RESULT_TYPES),
      winning_margin: str(50, true),
      player_of_the_match_id: id(false, true),
      finalized_at: date(),
      finalized_by: id(),
    },
  },
  {
    tableName: 'player_match_statistics',
    primaryKey: 'stat_id',
    attributes: {
      stat_id: id(true),
      match_id: id(),
      player_id: id(),
      runs_scored: smallint(false, 0),
      balls_faced: smallint(false, 0),
      fours: smallint(false, 0),
      sixes: smallint(false, 0),
      strike_rate: dec(6, 2, true),
      overs_bowled: dec(4, 1, false, 0),
      runs_conceded: smallint(false, 0),
      wickets_taken: smallint(false, 0),
      economy_rate: dec(5, 2, true),
      catches: smallint(false, 0),
      run_outs: smallint(false, 0),
      stumpings: smallint(false, 0),
      computed_at: date(),
    },
  },
  {
    tableName: 'player_rating_events',
    primaryKey: 'rating_event_id',
    attributes: {
      rating_event_id: id(true),
      player_id: id(),
      match_id: id(false, true),
      event_type: enumCol(RATING_EVENT_TYPES),
      rating_dimension: enumCol(RATING_DIMENSIONS),
      rating_delta: dec(6, 2),
      resulting_value: dec(6, 2, true),
      created_by: id(false, true),
      created_at: date(),
    },
  },
  {
    tableName: 'match_intro',
    primaryKey: 'intro_id',
    attributes: {
      intro_id: id(true),
      match_id: id(),
      countdown_enabled: bool(false, true),
      background_music_enabled: bool(false, true),
      playing_xi_confirmed_team_a: bool(false, false),
      playing_xi_confirmed_team_b: bool(false, false),
      intro_played_at: date(true),
    },
  },
  {
    tableName: 'live_match_sessions',
    primaryKey: 'viewer_session_id',
    attributes: {
      viewer_session_id: id(true),
      match_id: id(),
      user_id: id(false, true),
      socket_id: str(50),
      connected_at: date(),
      disconnected_at: date(true),
    },
  },
  {
    tableName: 'notifications',
    primaryKey: 'notification_id',
    attributes: {
      notification_id: id(true),
      user_id: id(),
      notification_type: enumCol(NOTIFICATION_TYPES),
      title: str(150),
      body: str(500),
      related_entity_type: str(50, true),
      related_entity_id: id(false, true),
      delivery_channel: enumCol(DELIVERY_CHANNELS, false, 'PUSH'),
      delivery_status: enumCol(DELIVERY_STATUSES, false, 'PENDING'),
      created_at: date(),
      read_at: date(true),
    },
  },
  {
    tableName: 'audit_logs',
    primaryKey: 'log_id',
    attributes: {
      log_id: id(true),
      actor_user_id: id(false, true),
      actor_role: str(30, true),
      action: str(100),
      resource_type: str(50),
      resource_id: id(),
      before_data: json(true),
      after_data: json(true),
      ip_address: str(45, true),
      request_id: id(false, true),
      created_at: date(),
    },
  },
  {
    tableName: 'support_tickets',
    primaryKey: 'ticket_id',
    attributes: {
      ticket_id: id(true),
      raised_by: id(),
      category: enumCol(SUPPORT_CATEGORIES),
      description: text(),
      related_entity_type: str(50, true),
      related_entity_id: id(false, true),
      status: enumCol(SUPPORT_STATUSES, false, 'OPEN'),
      assigned_to: id(false, true),
      created_at: date(),
      resolved_at: date(true),
    },
  },
];

// ---- associations ----
// Each entry describes a belongsTo (many-to-one) relationship driven by a
// foreign key column. `as`/`hasManyAs` give explicit, collision-free alias
// names since several tables (e.g. score_events) have multiple FK columns
// pointing at the same target table (players).
type AssociationDefinition = {
  from: string;
  fk: string;
  to: string;
  targetKey?: string;
  as: string;
  hasManyAs?: string;
};

const associationDefinitions: AssociationDefinition[] = [
  { from: 'players', fk: 'user_id', to: 'users', as: 'user', hasManyAs: 'playerProfile' },
  { from: 'players', fk: 'bfam_id', to: 'users', targetKey: 'bfam_id', as: 'bfamUser' },
  { from: 'teams', fk: 'created_by', to: 'users', as: 'creator', hasManyAs: 'createdTeams' },
  { from: 'team_members', fk: 'team_id', to: 'teams', as: 'team', hasManyAs: 'members' },
  {
    from: 'team_members',
    fk: 'player_id',
    to: 'players',
    as: 'player',
    hasManyAs: 'teamMemberships',
  },
  { from: 'team_invitations', fk: 'team_id', to: 'teams', as: 'team', hasManyAs: 'invitations' },
  {
    from: 'team_invitations',
    fk: 'invited_player_id',
    to: 'players',
    as: 'invitedPlayer',
    hasManyAs: 'teamInvitations',
  },
  { from: 'team_invitations', fk: 'invited_by', to: 'users', as: 'invitedByUser' },
  { from: 'team_join_requests', fk: 'team_id', to: 'teams', as: 'team', hasManyAs: 'joinRequests' },
  {
    from: 'team_join_requests',
    fk: 'player_id',
    to: 'players',
    as: 'player',
    hasManyAs: 'teamJoinRequests',
  },
  { from: 'team_join_requests', fk: 'responded_by', to: 'users', as: 'respondedByUser' },
  { from: 'turfs', fk: 'owner_id', to: 'users', as: 'owner', hasManyAs: 'ownedTurfs' },
  { from: 'turf_pricing', fk: 'turf_id', to: 'turfs', as: 'turf', hasManyAs: 'pricing' },
  {
    from: 'turf_staff_assignments',
    fk: 'turf_id',
    to: 'turfs',
    as: 'turf',
    hasManyAs: 'staffAssignments',
  },
  {
    from: 'turf_staff_assignments',
    fk: 'staff_user_id',
    to: 'users',
    as: 'staffUser',
    hasManyAs: 'staffAssignments',
  },
  { from: 'turf_staff_assignments', fk: 'assigned_by', to: 'users', as: 'assignedByUser' },
  {
    from: 'turf_availability_blocks',
    fk: 'turf_id',
    to: 'turfs',
    as: 'turf',
    hasManyAs: 'availabilityBlocks',
  },
  { from: 'turf_availability_blocks', fk: 'created_by', to: 'users', as: 'createdByUser' },
  { from: 'turf_images', fk: 'turf_id', to: 'turfs', as: 'turf', hasManyAs: 'images' },
  { from: 'turf_facilities', fk: 'turf_id', to: 'turfs', as: 'turf', hasManyAs: 'facilities' },
  {
    from: 'turf_operating_hours',
    fk: 'turf_id',
    to: 'turfs',
    as: 'turf',
    hasManyAs: 'operatingHours',
  },
  { from: 'bookings', fk: 'turf_id', to: 'turfs', as: 'turf', hasManyAs: 'bookings' },
  { from: 'bookings', fk: 'booked_by', to: 'users', as: 'bookedByUser', hasManyAs: 'bookings' },
  { from: 'bookings', fk: 'cancelled_by', to: 'users', as: 'cancelledByUser' },
  { from: 'matches', fk: 'booking_id', to: 'bookings', as: 'booking', hasManyAs: 'matches' },
  {
    from: 'matches',
    fk: 'organizer_id',
    to: 'users',
    as: 'organizer',
    hasManyAs: 'organizedMatches',
  },
  { from: 'matches', fk: 'assigned_scorer_id', to: 'users', as: 'assignedScorer' },
  { from: 'match_teams', fk: 'match_id', to: 'matches', as: 'match', hasManyAs: 'matchTeams' },
  { from: 'match_teams', fk: 'team_id', to: 'teams', as: 'team', hasManyAs: 'matchTeams' },
  { from: 'match_players', fk: 'match_id', to: 'matches', as: 'match', hasManyAs: 'matchPlayers' },
  {
    from: 'match_players',
    fk: 'player_id',
    to: 'players',
    as: 'player',
    hasManyAs: 'matchAppearances',
  },
  {
    from: 'match_players',
    fk: 'match_team_id',
    to: 'match_teams',
    as: 'matchTeam',
    hasManyAs: 'matchPlayers',
  },
  {
    from: 'match_invitations',
    fk: 'match_id',
    to: 'matches',
    as: 'match',
    hasManyAs: 'invitations',
  },
  {
    from: 'match_invitations',
    fk: 'invited_player_id',
    to: 'players',
    as: 'invitedPlayer',
    hasManyAs: 'matchInvitations',
  },
  { from: 'match_invitations', fk: 'invited_by', to: 'users', as: 'invitedByUser' },
  {
    from: 'player_replacements',
    fk: 'match_id',
    to: 'matches',
    as: 'match',
    hasManyAs: 'playerReplacements',
  },
  {
    from: 'player_replacements',
    fk: 'vacating_player_id',
    to: 'players',
    as: 'vacatingPlayer',
    hasManyAs: 'replacementsVacated',
  },
  {
    from: 'player_replacements',
    fk: 'replacement_player_id',
    to: 'players',
    as: 'replacementPlayer',
    hasManyAs: 'replacementsFilled',
  },
  { from: 'player_replacements', fk: 'initiated_by', to: 'users', as: 'initiatedByUser' },
  {
    from: 'payment_obligations',
    fk: 'booking_id',
    to: 'bookings',
    as: 'booking',
    hasManyAs: 'paymentObligations',
  },
  {
    from: 'payment_obligations',
    fk: 'player_id',
    to: 'players',
    as: 'player',
    hasManyAs: 'paymentObligations',
  },
  { from: 'payments', fk: 'payer_id', to: 'users', as: 'payer', hasManyAs: 'payments' },
  { from: 'payments', fk: 'collected_by', to: 'users', as: 'collectedByUser' },
  {
    from: 'payment_allocations',
    fk: 'payment_id',
    to: 'payments',
    as: 'payment',
    hasManyAs: 'allocations',
  },
  {
    from: 'payment_allocations',
    fk: 'obligation_id',
    to: 'payment_obligations',
    as: 'obligation',
    hasManyAs: 'allocations',
  },
  { from: 'refunds', fk: 'payment_id', to: 'payments', as: 'payment', hasManyAs: 'refunds' },
  { from: 'refunds', fk: 'initiated_by', to: 'users', as: 'initiatedByUser' },
  {
    from: 'payment_events',
    fk: 'payment_id',
    to: 'payments',
    as: 'payment',
    hasManyAs: 'events',
  },
  { from: 'innings', fk: 'match_id', to: 'matches', as: 'match', hasManyAs: 'innings' },
  {
    from: 'innings',
    fk: 'batting_match_team_id',
    to: 'match_teams',
    as: 'battingTeam',
    hasManyAs: 'inningsBatting',
  },
  {
    from: 'innings',
    fk: 'bowling_match_team_id',
    to: 'match_teams',
    as: 'bowlingTeam',
    hasManyAs: 'inningsBowling',
  },
  {
    from: 'score_events',
    fk: 'innings_id',
    to: 'innings',
    as: 'innings',
    hasManyAs: 'scoreEvents',
  },
  {
    from: 'score_events',
    fk: 'striker_player_id',
    to: 'players',
    as: 'striker',
    hasManyAs: 'scoreEventsAsStriker',
  },
  {
    from: 'score_events',
    fk: 'non_striker_player_id',
    to: 'players',
    as: 'nonStriker',
    hasManyAs: 'scoreEventsAsNonStriker',
  },
  {
    from: 'score_events',
    fk: 'bowler_player_id',
    to: 'players',
    as: 'bowler',
    hasManyAs: 'scoreEventsAsBowler',
  },
  {
    from: 'score_events',
    fk: 'dismissed_player_id',
    to: 'players',
    as: 'dismissedPlayer',
    hasManyAs: 'scoreEventsAsDismissed',
  },
  {
    from: 'score_events',
    fk: 'fielder_player_id',
    to: 'players',
    as: 'fielder',
    hasManyAs: 'scoreEventsAsFielder',
  },
  { from: 'score_events', fk: 'recorded_by', to: 'users', as: 'recordedByUser' },
  {
    from: 'score_events',
    fk: 'correction_reference_id',
    to: 'score_events',
    as: 'correctionReference',
    hasManyAs: 'corrections',
  },
  { from: 'match_results', fk: 'match_id', to: 'matches', as: 'match', hasManyAs: 'results' },
  {
    from: 'match_results',
    fk: 'winning_match_team_id',
    to: 'match_teams',
    as: 'winningTeam',
    hasManyAs: 'wonResults',
  },
  {
    from: 'match_results',
    fk: 'player_of_the_match_id',
    to: 'players',
    as: 'playerOfTheMatch',
    hasManyAs: 'playerOfTheMatchAwards',
  },
  { from: 'match_results', fk: 'finalized_by', to: 'users', as: 'finalizedByUser' },
  {
    from: 'player_match_statistics',
    fk: 'match_id',
    to: 'matches',
    as: 'match',
    hasManyAs: 'playerStatistics',
  },
  {
    from: 'player_match_statistics',
    fk: 'player_id',
    to: 'players',
    as: 'player',
    hasManyAs: 'matchStatistics',
  },
  {
    from: 'player_rating_events',
    fk: 'player_id',
    to: 'players',
    as: 'player',
    hasManyAs: 'ratingEvents',
  },
  {
    from: 'player_rating_events',
    fk: 'match_id',
    to: 'matches',
    as: 'match',
    hasManyAs: 'playerRatingEvents',
  },
  { from: 'player_rating_events', fk: 'created_by', to: 'users', as: 'createdByUser' },
  { from: 'match_intro', fk: 'match_id', to: 'matches', as: 'match', hasManyAs: 'intro' },
  {
    from: 'live_match_sessions',
    fk: 'match_id',
    to: 'matches',
    as: 'match',
    hasManyAs: 'liveSessions',
  },
  {
    from: 'live_match_sessions',
    fk: 'user_id',
    to: 'users',
    as: 'user',
    hasManyAs: 'liveSessions',
  },
  { from: 'notifications', fk: 'user_id', to: 'users', as: 'user', hasManyAs: 'notifications' },
  { from: 'audit_logs', fk: 'actor_user_id', to: 'users', as: 'actor', hasManyAs: 'auditLogs' },
  {
    from: 'support_tickets',
    fk: 'raised_by',
    to: 'users',
    as: 'raisedByUser',
    hasManyAs: 'raisedSupportTickets',
  },
  {
    from: 'support_tickets',
    fk: 'assigned_to',
    to: 'users',
    as: 'assignedToUser',
    hasManyAs: 'assignedSupportTickets',
  },
];

export function initModels(sequelize: Sequelize) {
  const models = Object.fromEntries(
    tableModelDefinitions.map((definition) => [
      definition.tableName,
      sequelize.define(definition.tableName, definition.attributes, {
        tableName: definition.tableName,
        underscored: true,
        timestamps: false,
      }),
    ]),
  );

  for (const association of associationDefinitions) {
    const source = models[association.from];
    const target = models[association.to];
    source.belongsTo(target, {
      foreignKey: association.fk,
      targetKey: association.targetKey,
      as: association.as,
    });
    if (association.hasManyAs) {
      target.hasMany(source, {
        foreignKey: association.fk,
        sourceKey: association.targetKey,
        as: association.hasManyAs,
      });
    }
  }

  return models;
}
